# Generated by Django 4.0.4 on 2022-05-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_remove_news_place_of_news_news_place_of_news'),
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='place_city',
        ),
        migrations.AddField(
            model_name='place',
            name='place_city',
            field=models.ManyToManyField(related_name='city_place', to='mainApp.city'),
        ),
        migrations.RemoveField(
            model_name='place',
            name='place_region',
        ),
        migrations.AddField(
            model_name='place',
            name='place_region',
            field=models.ManyToManyField(related_name='region_place', to='mainApp.region'),
        ),
    ]
