# Generated by Django 4.0.4 on 2022-05-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_location_alter_place_latitude_alter_place_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
