# Generated by Django 4.0.4 on 2022-05-31 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_rename_name_location_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='map.location'),
        ),
    ]
