# Generated by Django 4.0.4 on 2022-04-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='place_news',
            new_name='place_of_news',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='type',
            new_name='type_of_place',
        ),
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.FloatField(blank=True, default=44.796942),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.FloatField(blank=True, default=20.468565),
        ),
    ]
