# Generated by Django 4.0.4 on 2022-05-16 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_alter_place_type_of_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='region_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.city'),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
