# Generated by Django 4.0.4 on 2022-05-28 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_alter_news_place_of_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='place_of_news',
        ),
    ]
