# Generated by Django 4.0.4 on 2022-05-16 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_region_region_city_alter_country_country_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='region_city',
        ),
    ]
