# Generated by Django 4.0.4 on 2022-05-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
        ('mainApp', '0003_remove_news_place_of_news_news_place_of_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='place_of_news',
        ),
        migrations.AddField(
            model_name='news',
            name='place_of_news',
            field=models.ManyToManyField(related_name='place_news', to='map.place'),
        ),
    ]
