# Generated by Django 4.0.4 on 2022-04-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_alter_member_options_alter_news_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='description',
            field=models.TextField(default='Opis'),
        ),
    ]
