# Generated by Django 4.0.4 on 2022-05-24 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_remove_news_place_of_news_news_place_of_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={},
        ),
    ]
