# Generated by Django 4.0.4 on 2022-05-04 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_alter_city_city_alter_region_city_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='city_area',
        ),
        migrations.AddField(
            model_name='city',
            name='city_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.region'),
        ),
    ]
