# Generated by Django 4.0.4 on 2022-05-16 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_remove_region_region_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='region_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.country'),
        ),
    ]
