# Generated by Django 4.0.4 on 2022-05-10 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_alter_member_password_alter_member_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='city_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.city'),
        ),
    ]
