# Generated by Django 4.0.4 on 2022-05-10 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_alter_news_city_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='city_place',
            new_name='news_region',
        ),
        migrations.AddField(
            model_name='news',
            name='news_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.city'),
        ),
    ]
