# Generated by Django 4.0.4 on 2022-05-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_rename_city_place_news_news_region_news_news_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='type_of_place',
            field=models.CharField(blank=True, choices=[('ostalo', 'ostalo'), ('eat', 'eat'), ('sleep', 'sleep'), ('attraction', 'attraction')], default='ostalo', max_length=10, null=True),
        ),
    ]
