# Generated by Django 4.0.4 on 2022-05-11 10:18

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_alter_place_type_of_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='type_of_place',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('eat', 'eat'), ('sleep', 'sleep'), ('attraction', 'attraction')], max_length=10, null=True),
        ),
    ]
