# Generated by Django 4.0.4 on 2022-05-11 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_alter_place_type_of_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='city',
            new_name='place_city',
        ),
        migrations.AddField(
            model_name='place',
            name='place_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.region'),
        ),
    ]
